# Generated by Django 4.2.2 on 2023-07-28 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='alrvoted',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
